### ISSUE TITLE
The game doesn't load into the main menu with the newest forge version.

### ISSUE THREAD

**Issue by johannesspinnenschreck** [gamma-02/moss-fix-arch-edition#1]
I have installed the newest version of forge and the newest version of the mod and get these logs.

[crash-2022-09-25_12.48.43-fml.txt](https://github.com/gamma-02/moss-fix-arch-edition/files/9640564/crash-2022-09-25_12.48.43-fml.txt)
[latest.log](https://github.com/gamma-02/moss-fix-arch-edition/files/9640565/latest.log)

**Comment by gamma-02** [comment]
did you install Architectury API?

**Comment by johannesspinnenschreck** [comment]
No, I hadn't.
It works now, that I have, thx.

**Comment by gamma-02** [comment]
for all ye who enter here to submit a new issue, note you need Architectury API.
