### ISSUE TITLE
it spawns way too often (especially in other dimensions)

### ISSUE THREAD

**Issue by Razzyreather** [gamma-02/moss-fix-arch-edition#2]
playing this with twilight forest and they literally spawn like every 20 blocks (on the surface)

**Comment by gamma-02** [comment]
...uh what?
I'm going to need a lot more information than that, such as: what spawns too often and(if this is actually my problem and not another mod's) which dimensions are affected?

**Comment by gamma-02** [comment]
*submits bug report*
*bug is probably not from my mod*
*leaves*
*refuses to elaborate*

so basically, I'm going to ignore this and say
### _**n o t   m y   p r o b l e m**_
