### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by Estrelaura** [gamma-02/moss-fix-arch-edition#3]
Using bonemeal on moss creates a debug spam on the log. This makes hard seeing the log history, specially if you're managing a server.

**Comment by gamma-02** [comment]
let me see about that! I think I may have left a print statement in there. What version were you using it on?

Out of curiosity, how did you figure out that it was my mod causing it? I've been looking for a mod that adds attribution to Sysem.out.println calls...

**Comment by gamma-02** [comment]
Anyway, this fix will be in the mods on Modrinth and CF when I get around to releasing the next batch of updates

**Comment by Estrelaura** [comment]
> let me see about that! I think I may have left a print statement in there. What version were you using it on?
> 
> Out of curiosity, how did you figure out that it was my mod causing it? I've been looking for a mod that adds attribution to Sysem.out.println calls...

Just a bit of deduction. I was using it on Quilt 1.20.1 and usually i make tests and keep an eye on what everything does. I also never install too many mods at a time, and i didn't have any othe mod changing moss behavior. Since the log was generated only when bonemealing moss, i figured it would be a debug leftover from here. Thanks for solving it anyway.

**Comment by gamma-02** [comment]
ahhh, yeah, makes sense. How does it work with Quilt? I can compile specific versions for quilt as well if you need them
